<?php

/**
 * @file
 * Contains cl_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function cl_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cl_api module.
    case 'help.page.cl_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('API for Coffee Love') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function cl_api_node_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'cupping_session') {
    if (empty($entity->original)) {
      // New entity.
      $entity->field_session_id = uniqid();
    }
  }
}
